In [ ]:
pip install pandas

In [7]:
pip install plotly

Collecting plotly
  Downloading plotly-4.9.0-py2.py3-none-any.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 3.5 MB/s eta 0:00:01    |██████████▋                     | 4.3 MB 3.5 MB/s eta 0:00:03
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from plotly) (1.15.0)
Collecting retrying>=1.3.3
  Downloading retrying-1.3.3.tar.gz (10 kB)
Building wheels for collected packages: retrying
  Building wheel for retrying (setup.py) ... done
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11430 sha256=1ee6b713cf5f27a69d71661fd71cad9c57dbdeee9bf0360a33549cc822e9df47
  Stored in directory: /home/jovyan/.cache/pip/wheels/f9/8d/8d/f6af3f7f9eea3553bc2fe6d53e4b287dad18b06a861ac56ddf
Successfully built retrying
Installing collected packages: retrying, plotly
Successfully installed plotly-4.9.0 retrying-1.3.3
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
from pandas import DataFrame
from datetime import datetime
import plotly.graph_objects as go
import sys

In [9]:
period_S = 10
period_XL = 25

eth_1m = pd.read_csv('ETH_history_1m_S.csv')
eth_1m['MA'] = (eth_1m['high'] + eth_1m['low'])/2
eth_1m['MA_S']= round(eth_1m['MA'].rolling(window = period_S).mean(),3)
eth_1m['MA_XL']= round(eth_1m['MA'].rolling(window = period_XL).mean(),3)
eth =eth_1m.set_index('timestamp')

In [11]:
eth.tail()

,high,low,open,close,MA,MA_S,MA_XL
timestamp,,,,,,,
2020-08-06T16:57:00.000Z,399.25,398.95,399.30,399.05,399.100,398.980,398.528
2020-08-06T16:58:00.000Z,399.30,399.00,399.05,399.10,399.150,399.073,398.551
2020-08-06T16:59:00.000Z,399.15,399.05,399.10,399.10,399.100,399.135,398.578
2020-08-06T17:00:00.000Z,399.10,399.05,399.10,399.05,399.075,399.138,398.603
2020-08-06T17:01:00.000Z,399.65,399.05,399.05,399.65,399.350,399.150,398.647

In [ ]:
def backtest(data,period_XL):
    capital = 100
    trades = []
    
    candle_red=False
    candle_green=False
    
    SL = None
    TP = None
    Trade_On = False
    S_Above = False
    
    for index, row in data.iloc[period_XL:].iterrows():
        
         if row['close']>= row['open']:
            candle_red=False
            candle_green=True
            
        while not Trade_On:
            while candle_green:
                if S_Above = False and

In [ ]:
gfgfgf